Traceback (most recent call last):
  File "bco_editor", line 256, in main
    client.server_info()
  File "build/bdist.macosx-10.11-intel/egg/pymongo/mongo_client.py", line 1206, in server_info
    read_preference=ReadPreference.PRIMARY)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.macosx-10.11-intel/egg/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.macosx-10.11-intel/egg/pymongo/mongo_client.py", line 870, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.macosx-10.11-intel/egg/pymongo/server.py", line 168, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.macosx-10.11-intel/egg/pymongo/pool.py", line 852, in get_socket
    sock_info.check_auth(all_credentials)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/pool.py", line 570, in check_auth
    auth.authenticate(credentials, self)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/auth.py", line 486, in authenticate
    auth_func(credentials, sock_info)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/auth.py", line 209, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/pool.py", line 477, in command
    collation=collation)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: Authentication failed.
